stages:
  - clean
  - build
  - deploy


before_script:
  - BUILD_HOME="/mnt/build_home"
  - FRONTEND_SRC="$BUILD_HOME/elgo-nest-frontend/$CI_COMMIT_REF_NAME"
  - APP_HOME="/mnt/websites/elgo-nest/$CI_COMMIT_REF_NAME"
  - BUILD_COMMAND="build-web-$CI_COMMIT_REF_NAME";

clean:
  stage: clean
  only:
    - master
    - develop
  script:
    - echo "===========Clean=============="
    - rm -rf $FRONTEND_SRC
    - mkdir -p $FRONTEND_SRC



build:
  stage: build
  only:
    - master
    - develop
  script:
    - echo "===========Build==========="

    - git clone http://oauth2:2vEyDbk7vypebA1FByUZ@www.repo.elgo.cc/elgo/elgo-frontend.git -b $CI_COMMIT_REF_NAME $FRONTEND_SRC
    - cd $FRONTEND_SRC; cnpm i;cnpm run $BUILD_COMMAND ;


deploy:
  stage: deploy
  only:
    - master
    - develop
  script:
    - echo "===========Deploy==========="
    - mkdir -p $APP_HOME
    - cp -rf $FRONTEND_SRC/dist/* $APP_HOME


