stages:
  - clean
  - build
  - deploy


before_script:
  - BUILD_HOME="/mnt/build_home"
  - >
      if [ "$CI_COMMIT_REF_NAME" = "develop" ]; then
      FRONTEND_SRC="$BUILD_HOME/effwork-frontend/develop";
      APP_HOME="/mnt/websites/effwork/develop";
      BUILD_COMMAND="build-web-dev"
      fi;
      if [ "$CI_COMMIT_REF_NAME" = "master" ]; then
      FRONTEND_SRC="$BUILD_HOME/effwork-frontend/production";
      APP_HOME="/mnt/websites/effwork/production";
      BUILD_COMMAND="build-web"
      fi;

clean:
  stage: clean
  only:
    - develop
    - master
  script:
    - echo "===========Clean=============="
    - rm -rf $FRONTEND_SRC
    - mkdir -p $FRONTEND_SRC


build:
  stage: build
  only:
    - develop
    - master
  script:
    - echo "===========Build==========="
    - git clone http://gitlab+deploy-token-20:-3ziAm63EZyETZiXWa1n@www.repo.effwork.net:8025/eff-work/effwork-pc.git -b $CI_COMMIT_REF_NAME $FRONTEND_SRC
    - cd $FRONTEND_SRC; cnpm i;  cnpm run $BUILD_COMMAND ;


deploy:
  stage: deploy
  only:
    - develop
    - master
  script:
    - echo "===========Deploy==========="
    - mkdir -p $APP_HOME
    - cp -rf $FRONTEND_SRC/dist/* $APP_HOME


