name: Build Elgo Frontend
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    name: Install And Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Get Branch Name
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        uses: nelonoel/branch-name@v1

      - name: Set Deploy Target
        run: |
          echo "TARGET=${{ secrets.ALIYUN_DIR_TARGET }}/${BRANCH_NAME}" >> $GITHUB_ENV

      - name: use NodeJs 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependency & Build
        run: |
          npm install --legacy-peer-deps
          npm run build-web-${BRANCH_NAME}

      - name: Deploy to Aliyun
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SERVER_TOKEN }}
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.ALIYUN_SERVER }}
          REMOTE_USER: ${{ secrets.ALIYUN_SERVER_USER }}

      - name: Send mail
        uses: cinotify/github-action@main
        with:
          to: 'neal@elgo.cc'
          subject: 'Elgo Frontend Build Done'
          body: 'Elgo Frontend Build for ${BRANCH_NAME} Done'




